### ISSUE TITLE
undefined local variable or method `wait_until_has_element_name'

### ISSUE THREAD

**Issue by ArtemVarnavskiy** [hoangtaiki/appom#2]
class LoginPage < Appom::Page
  
  element :input_login, :xpath, "//XCUIElementTypeTextField"
  
  def authorization(login)
      wait_until_has_input_login
      input_login.send_keys(login)
  end
 
end

**Problem**
When i call a method **authorization(login)**, i get error:

undefined local variable or method `wait_until_has_input_login' for #<LoginPage:0x00007fa744613788>
      Did you mean?  wait_until_get_not_empty (NameError)

**Comment by hoangtaiki** [comment]
@ArtemVarnavskiy Please rename it to `has_input_login`

**Comment by hoangtaiki** [comment]
I rename this function to `has_element`

```
##
# Check element exist
# We will try to find all elements with *find_args
# Condition is pass when response is not empty
#
def create_existence_checker(element_name, *find_args)
  method_name = "has_#{element_name}"
  create_helper_method(method_name, *find_args) do
    define_method(method_name) do |*runtime_args|
      args = merge_args(find_args, runtime_args)
      wait_until('at least one element exists', *args)
    end
  end
end
```

**Comment by ArtemVarnavskiy** [comment]
@hoangtaiki Thank! It works

**Comment by ArtemVarnavskiy** [comment]
@hoangtaiki It would be great if could use Explicit Wait for **has_no_element**
example:
has_no_element(10)

**Comment by hoangtaiki** [comment]
Great idea. I will create an issue and implement it.

**Comment by hoangtaiki** [comment]
@ArtemVarnavskiy I will implement it in this issue
https://github.com/hoangtaiki/appom/issues/3#issue-450725603
